// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYnknIcgDDrL6Nmt6kl_EEcHFH-zYVLYc',
    appId: '1:521275073342:web:14955582a5a915c0e1426f',
    messagingSenderId: '521275073342',
    projectId: 'jako-prod',
    authDomain: 'jako-prod.firebaseapp.com',
    storageBucket: 'jako-prod.firebasestorage.app',
    measurementId: 'G-MS5D4HFDPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrJ74dUBxKgGqmSDwtvZ9pfhcy6ABZL4',
    appId: '1:521275073342:android:1115b7bcd028ce70e1426f',
    messagingSenderId: '521275073342',
    projectId: 'jako-prod',
    storageBucket: 'jako-prod.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYnknIcgDDrL6Nmt6kl_EEcHFH-zYVLYc',
    appId: '1:521275073342:web:700e2c145deba960e1426f',
    messagingSenderId: '521275073342',
    projectId: 'jako-prod',
    authDomain: 'jako-prod.firebaseapp.com',
    storageBucket: 'jako-prod.firebasestorage.app',
    measurementId: 'G-2JS06CSJW5',
  );

}